[mdzk]
title = "Minhas Notas"
description = "Registro do que eu sei"
authors = ["ImGabe <gabrielpmonte@gmail.com>"]
language = "pt-br"
src = "notes"

[build]
create-missing = false
build-dir = "book"

[output.html]
cname = "notes.imgabe.me"
default-theme = "basalt"
preferred-dark-theme = "basalt"
git-repository-icon = "fa-github"
git-repository-url = "https://github.com/imgabe/notes"
edit-url-template = "https://github.com/imgabe/notes/edit/main/{path}"
no-section-label = true
site-url = "/"

[output.html.print]
enable = false

[output.html.fold]
enable = true
level = 1
